name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Give write permission to push tags

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint -r requirements.txt

    - name: Run Pylint
      run: |
        pylint **/*.py || true

    - name: Tag upon success
      if: success()
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git tag pylint-pass-${{ github.sha }}
        git push origin pylint-pass-${{ github.sha }}

